apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "micro-ssr.fullname" . }}
  labels:
    {{- include "micro-ssr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "micro-ssr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "micro-ssr.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "micro-ssr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- if .Values.microSSR.home }}
            - env SSR_HOME_TARGET="{{ .Values.microSSR.home }}"
            {{- end }}
            - yarn start
          env:
            {{- if .Values.microSSR.home }}
            - name: SSR_HOME_TARGET
              value: {{ quote .Values.microSSR.home }}
            {{- end }}
            {{- if .Values.microSSR.about }}
            - name: SSR_ABOUT_TARGET
              value: {{ .Values.microSSR.about }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
