{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "micro-ssr.serviceAccountName" . }}
  labels:
{{ include "micro-ssr.labels" . | nindent 4 }}
{{- end -}}
